[build]
  command = "make"
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "github.com/saschazar21/go-web-push-server"
  GO111MODULE = "on"
  GOARCH = "amd64"
  GOOS = "linux"

[[redirects]]
  from = "/api/v1/push/:id"
  to = "/.netlify/functions/v1_push"
  status = 200
  force = true

[[redirects]]
  from = "/api/v1/subscribe"
  to = "/.netlify/functions/v1_subscribe"
  status = 200
  force = true

[[redirects]]
  from = "/api/v1/unsubscribe/:id"
  to = "/.netlify/functions/v1_unsubscribe"
  status = 200
  force = true