[build]
  command = "make"
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "github.com/saschazar21/go-web-push-server"
  GO111MODULE = "on"
  GOARCH = "amd64"
  GODEBUG = "http2client=0"
  GOOS = "linux"

[template.environment]
  POSTGRES_CONNECTION_STRING = "Set this to your PostgreSQL connection string, e.g. postgres://..."
  VAPID_EXPIRY_DURATION = "The VAPID JWT lifetime in seconds"
  VAPID_PRIVATE_KEY = "The VAPID private key in PEM format"
  VAPID_SUBJECT = "A contact e-mail address for the VAPID JWT"
  BASIC_AUTH_PASSWORD = "A password for the basic auth strategy on /api/v1 routes"

[[redirects]]
  from = "/api/v1/push"
  to = "/.netlify/functions/v1_push"
  status = 200
  force = true

[[redirects]]
  from = "/api/v1/push/:id"
  to = "/.netlify/functions/v1_push"
  status = 200
  force = true

[[redirects]]
  from = "/api/v1/subscribe"
  to = "/.netlify/functions/v1_subscribe"
  status = 200
  force = true

[[redirects]]
  from = "/api/v1/unsubscribe"
  to = "/.netlify/functions/v1_unsubscribe"
  status = 200
  force = true

[[redirects]]
  from = "/api/v1/unsubscribe/:id"
  to = "/.netlify/functions/v1_unsubscribe"
  status = 200
  force = true

# Only for demo purposes, return valid content-type header for the web manifest

[[headers]]
  for = "/manifest.webmanifest"
    [headers.values]
    Content-Type = "application/manifest+json"

# Only for demo purposes, check source code in netlify/edge-functions/demo.js

[[redirects]]
  from = "/demo/subscribe"
  to = "/.netlify/edge-functions/demo/subscribe"
  status = 200
  force = true

# Only for demo purposes, check source code in netlify/edge-functions/dad-joke.js

[[redirects]]
  from = "/demo/dad-joke"
  to = "/.netlify/edge-functions/demo/dad-joke"
  status = 200
  force = true