[build]
  command = "make netlify"
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "github.com/saschazar21/go-web-push-server"
  GO111MODULE = "on"
  GOARCH = "amd64"
  GOOS = "linux"