name: Outputs

on:
  workflow_call:
    outputs:
      short_sha:
        description: "The SHORT_SHA value of the current git commit"
        value: ${{ jobs.outputs.outputs.SHORT_SHA }}

jobs:
  outputs:
    name: Outputs
    runs-on: ubuntu-latest

    outputs:
      SHORT_SHA: ${{ steps.short_sha.outputs.SHORT_SHA }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set SHORT_SHA
        id: short_sha
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_OUTPUT
