name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    uses: ./.github/workflows/setup.yml

    steps:
      - name: Test
        run: make test
